services:
  db_test:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  test:
    build: .
    environment:
      ENV: test 
      DATABASE_URL_READER: postgresql://user:pass@db_test:5432/test_db
      DATABASE_URL_WRITER: postgresql://user:pass@db_test:5432/test_db
      SECRET_KEY: DeyLu5K0xn_MX-9HSCxHrn0lZ9ZDjk4b_Kw9U6cAUWJeaStr8NaJQnyB2JI-Yi-0oFd9ujlTgt0D35tTuCfPIw
    depends_on:
      db_test:
        condition: service_healthy
    command: pytest -q