services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      ENV: dev
      DATABASE_URL_READER: postgresql://user:pass@db:5432/db
      DATABASE_URL_WRITER: postgresql://user:pass@db:5432/db
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000