"""init tables

Revision ID: 65e89750eb9a
Revises: c7e520b362bd
Create Date: 2026-06-07 09:43:05.695708

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '65e89750eb9a'
down_revision: Union[str, Sequence[str], None] = 'c7e520b362bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
