"""

Revision ID: ae53f7f784b6
Revises: c9fde07c0dc5
Create Date: 2026-06-15 09:56:11.542867

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ae53f7f784b6'
down_revision: Union[str, Sequence[str], None] = 'c9fde07c0dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
