"""Fix timezone

Revision ID: c50d2f838e71
Revises: f2ddcc3b83e0
Create Date: 2026-06-09 14:21:23.821180

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c50d2f838e71'
down_revision: Union[str, Sequence[str], None] = 'f2ddcc3b83e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
