"""init tables

Revision ID: c7e520b362bd
Revises: 
Create Date: 2026-06-07 09:36:31.452897

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c7e520b362bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
