"""

Revision ID: c9fde07c0dc5
Revises: c50d2f838e71
Create Date: 2026-06-12 13:49:48.594921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fde07c0dc5'
down_revision: Union[str, Sequence[str], None] = 'c50d2f838e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('email', sa.String(), nullable=True))
    op.add_column('players', sa.Column('password', sa.String(), nullable=True))
    op.add_column('players', sa.Column('account_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_players_email'), 'players', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_email'), table_name='players')
    op.drop_column('players', 'account_type')
    op.drop_column('players', 'password')
    op.drop_column('players', 'email')
    # ### end Alembic commands ###
