"""init tables

Revision ID: d8e5da011720
Revises: de5709e69c8c
Create Date: 2026-06-07 09:54:27.045729

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'd8e5da011720'
down_revision: Union[str, Sequence[str], None] = 'de5709e69c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
