"""init tables

Revision ID: de5709e69c8c
Revises: 65e89750eb9a
Create Date: 2026-06-07 09:52:20.535260

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'de5709e69c8c'
down_revision: Union[str, Sequence[str], None] = '65e89750eb9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
