"""init tables

Revision ID: f07b53a488e8
Revises: d8e5da011720
Create Date: 2026-06-07 09:55:20.987779

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'f07b53a488e8'
down_revision: Union[str, Sequence[str], None] = 'd8e5da011720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
