name: CI - Tests

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tests with Docker Compose
        run: |
          make test-rebuild

      - name: Shutdown containers
        if: always()
        run: |
          make test-down